// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: errors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from errors.proto</summary>
public static partial class ErrorsReflection {

  #region Descriptor
  /// <summary>File descriptor for errors.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxlcnJvcnMucHJvdG8iwAEKBUVycm9yEh0KBm1vZHVsZRgBIAEoDjINLkVy",
          "cm9yLk1vZHVsZRIMCgRjb2RlGAIgASgEEg8KB21lc3NhZ2UYAyABKAkSFwoP",
          "ZXhjZXB0aW9uX3N0YWNrGAQgASgJImAKBk1vZHVsZRILCgdVTktOT1dOEAAS",
          "EAoMVVNFUl9TRVJWSUNFEAESEwoPQ0hFQ0tJTl9TRVJWSUNFEAISDwoLQURT",
          "X1NFUlZJQ0UQAxIRCg1TVEFUU19TRVJWSUNFEARiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Error), global::Error.Parser, new[]{ "Module", "Code", "Message", "ExceptionStack" }, null, new[]{ typeof(global::Error.Types.Module) }, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Error : pb::IMessage<Error> {
  private static readonly pb::MessageParser<Error> _parser = new pb::MessageParser<Error>(() => new Error());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Error> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ErrorsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Error() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Error(Error other) : this() {
    module_ = other.module_;
    code_ = other.code_;
    message_ = other.message_;
    exceptionStack_ = other.exceptionStack_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Error Clone() {
    return new Error(this);
  }

  /// <summary>Field number for the "module" field.</summary>
  public const int ModuleFieldNumber = 1;
  private global::Error.Types.Module module_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Error.Types.Module Module {
    get { return module_; }
    set {
      module_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 2;
  private ulong code_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 3;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "exception_stack" field.</summary>
  public const int ExceptionStackFieldNumber = 4;
  private string exceptionStack_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ExceptionStack {
    get { return exceptionStack_; }
    set {
      exceptionStack_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Error);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Error other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Module != other.Module) return false;
    if (Code != other.Code) return false;
    if (Message != other.Message) return false;
    if (ExceptionStack != other.ExceptionStack) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Module != 0) hash ^= Module.GetHashCode();
    if (Code != 0UL) hash ^= Code.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (ExceptionStack.Length != 0) hash ^= ExceptionStack.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Module != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Module);
    }
    if (Code != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Code);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Message);
    }
    if (ExceptionStack.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ExceptionStack);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Module != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Module);
    }
    if (Code != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Code);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (ExceptionStack.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ExceptionStack);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Error other) {
    if (other == null) {
      return;
    }
    if (other.Module != 0) {
      Module = other.Module;
    }
    if (other.Code != 0UL) {
      Code = other.Code;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.ExceptionStack.Length != 0) {
      ExceptionStack = other.ExceptionStack;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          module_ = (global::Error.Types.Module) input.ReadEnum();
          break;
        }
        case 16: {
          Code = input.ReadUInt64();
          break;
        }
        case 26: {
          Message = input.ReadString();
          break;
        }
        case 34: {
          ExceptionStack = input.ReadString();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Error message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Module {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("USER_SERVICE")] UserService = 1,
      [pbr::OriginalName("CHECKIN_SERVICE")] CheckinService = 2,
      [pbr::OriginalName("ADS_SERVICE")] AdsService = 3,
      [pbr::OriginalName("STATS_SERVICE")] StatsService = 4,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
